config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] 
  patch 'mylocation', to: 'users#update_mylocation'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :books, only: [:show, :new, :create, :edit, :update]
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  resources :searches, only: [:index] do
    member do
      get :request_users
      get :requested_users
      get :matched_users
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :relationshipmessages, only: [:create, :destroy]
  resources :messages, only: [:index, :create]
  patch 'accept_trade1', to: 'trade1s#accept_trade1'
  patch 'cancel_trade1', to: 'trade1s#cancel_trade1'
  patch 'accept_trade2', to: 'trade2s#accept_trade2'
  patch 'cancel_trade2', to: 'trade2s#cancel_trade2'
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :image, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :nationality, presence: true, length: { maximum: 50 }
  validates :gender, presence: true, length: { maximum: 50 }
  validates :age, presence: true
  validates :description, presence: true, length: { maximum: 255 }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find(params[:id])
  end
  
  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      flash[:success] = 'Profile Registeration Successful'
      redirect_to root_url
    else
      flash.now[:danger] = 'Profile Registration Failed'
      render :new
    end
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      flash[:success] = 'Profile Update Successful'
      redirect_to profile_path(id: @profile.id)
    else
      flash.now[:danger] = 'Profile Update Failed'
      render :edit
    end
  end
  
  private
  
  def profile_params
    params.require(:profile).permit(:image, :name, :nationality, :gender, :age, :description)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(profile) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :image, 'Image' %>
        <%= f.file_field :image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :nationality, 'Nationality' %>
        <%= f.text_field :nationality, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :gender, 'Gender' %>
        <%= f.text_field :gender, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :age, 'Age' %>
        <%= f.text_field :age, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :description, 'Description' %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>

      <%= f.submit 'Submit!', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="text-center">
  <h1>Update Profile</h1>
</div>

<%= render 'form', profile: @profile %>

app/views/profiles/new.html.erb
<div class="text-center">
  <h1>New Profile</h1>
</div>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<div class="profile">
  <div class="row">
    <aside class="col-xs-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @profile.name %></h3>
        </div>
        <div class="panel-body">
          <img class="media-object img-rounded img-responsive" src="<%= @profile.image %>" alt="">
        </div>
      </div>
    </aside>
    <div class="col-xs-8">
      <ul>
        <li>Nationality: <%= @profile.nationality %></li>
        <li>Gender: <%= @profile.gender %></li>
        <li>Age: <%= @profile.age %></li>
        <li>Description: <%= @profile.description %></li>
      </ul>
    </div>
  </div>
  <% if @profile.user_id == current_user.id %>
    <div class="row">
      <div class="col-xs-2">
        <%= link_to 'Update Profile', edit_profile_path(@profile), class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>