config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] 
  patch 'mylocation', to: 'users#update_mylocation'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :books, only: [:show, :new, :create, :edit, :update]
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  resources :searches, only: [:index] do
    member do
      get :request_users
      get :requested_users
      get :matched_users
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :relationshipmessages, only: [:create, :destroy]
  resources :messages, only: [:index, :create]
  patch 'accept_trade1', to: 'trade1s#accept_trade1'
  patch 'cancel_trade1', to: 'trade1s#cancel_trade1'
  patch 'accept_trade2', to: 'trade2s#accept_trade2'
  patch 'cancel_trade2', to: 'trade2s#cancel_trade2'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :image, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :author, presence: true, length: { maximum: 50 }
  validates :language, presence: true, length: { maximum: 50 }
  validates :page, presence: true
  validates :description, presence: true, length: { maximum: 255 }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :mylocations
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: 'User'
  
  validates :user_id, presence: true
  validates :recipient_id, presence: true
  validates :content, presence: true, length: { maximum: 50 }
end

app/models/mylocation.rb
class Mylocation < ApplicationRecord
  belongs_to :country
  has_many :users
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :image, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :nationality, presence: true, length: { maximum: 50 }
  validates :gender, presence: true, length: { maximum: 50 }
  validates :age, presence: true
  validates :description, presence: true, length: { maximum: 255 }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :request, class_name: 'User'
  
  validates :user_id, presence: true
  validates :request_id, presence: true
end

app/models/relationshipmessage.rb
class Relationshipmessage < ApplicationRecord
  belongs_to :user
  belongs_to :m_request, class_name: 'User'
  
  validates :user_id, presence: true
  validates :m_request_id, presence: true
end

app/models/trade1.rb
class Trade1 < ApplicationRecord
  belongs_to :user
  belongs_to :trader, class_name: 'User'
  
  validates :user_id, presence: true
  validates :trader_id, presence: true
end

app/models/trade2.rb
class Trade2 < ApplicationRecord
  belongs_to :user
  belongs_to :trader, class_name: 'User'
  
  validates :user_id, presence: true
  validates :trader_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  belongs_to :mylocation, optional: true
  has_one :book
  has_one :profile
  has_many :relationships
  has_many :requestings, through: :relationships, source: :request
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'request_id'
  has_many :requesteds, through: :reverses_of_relationship, source: :user
  has_many :relationshipmessages
  has_many :m_requestings, through: :relationshipmessages, source: :m_request
  has_many :reverses_of_relationshipmessage, class_name: 'Relationshipmessage', foreign_key: 'm_request_id'
  has_many :m_requesteds, through: :reverses_of_relationshipmessage, source: :user
  has_many :messages
  has_one :trade1
  has_one :trade2
  
  #Request & Unrequest button
  def send_request(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(request_id: other_user.id)
    end
  end
  
  def cancel_request(other_user)
    relationship = self.relationships.find_by(request_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def match_exist?(other_user)
    if self.requestings.include?(other_user) && self.requesteds.include?(other_user)
      return true
    else
      return false
    end
  end
  
  def requestings_exist?(other_user)
    self.requestings.include?(other_user)
  end
  
  #Message button
  def m_send_request(other_user)
    unless self == other_user
      self.relationshipmessages.find_or_create_by(m_request_id: other_user.id)
    end
  end
  
  def m_match_exist?(other_user)
    if self.m_requestings.include?(other_user) && self.m_requesteds.include?(other_user)
      return true
    else
      return false
    end
  end
  
  def m_match_in_users?(other_users)
    other_users.each do |user|
      if m_match_exist?(user)
        return true
      end
    end
    return false
  end
  
  def m_requestings_exist?(other_user)
    self.m_requestings.include?(other_user)
  end
  
  #After message_button is pushed
  def go_to_message(other_user)
    self.update(message_user_id: other_user.id)
    others = []
    other_relationships = self.relationshipmessages.where(user_id: self.id)
    other_relationships.each do |other|
      unless other.m_request_id == other_user.id
        others << other
      end
    end
    others.each do |other|
      other.destroy
    end
  end
  
  # Message 
  def send_message(other_user, content)
    unless self == other_user
      self.messages.build(recipient_id: other_user.id, content: content)
    end
  end
  
  #Trade1 button
  def trade1_accept_exchange(trade1)
    trade1.update(answer: 'Yes')
  end
  
  def trade1_cancel_exchange(trade1)
    trade1.update(answer: 'No')
  end
  
  def trade1_both_accept?(other_user)
    if other_user.trade1.present?
      if self.trade1.answer == 'Yes' && other_user.trade1.answer == 'Yes'
        return true
      else
        return false
      end
    else
      return false
    end
  end
  
  def trade1_user_accepted?(other_user)
    if self.trade1.answer == 'Yes' 
      return true
    else
      return false
    end
  end
  
  #Trade2 button
  def trade2_accept_exchange(trade2)
    trade2.update(answer: 'Yes')
  end
  
  def trade2_cancel_exchange(trade2)
    trade2.update(answer: 'No')
  end
  
  def trade2_user_accepted?(other_user)
    if self.trade2.answer == 'Yes' 
      return true
    else
      return false
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @mylocation = Mylocation.find_by(id: current_user.mylocation_id)
    @users = @mylocation.users
    @books = []
    @users.each do |user|
      if user.book.present?
        @books << user.book
      end
    end
  end
  
  def request_users
    @request_users = []
    current_user.requestings.each do |user|
      unless current_user.match_exist?(user)
        @request_users << user
      end
    end
  end
  
  def requested_users
    @requested_users = []
    current_user.requesteds.each do |user|
      unless current_user.match_exist?(user)
        @requested_users << user
      end
    end
  end
  
  def matched_users
    request_users = current_user.requestings
    @match_users = []
    request_users.each do |user|
      if current_user.match_exist?(user)
        @match_users << user
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/trade1s_helper.rb
module Trade1sHelper
end

app/helpers/trade2s_helper.rb
module Trade2sHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searches/index.html.erb
<div class="search">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-default" type="button"><%= link_to 'Sent Request', request_users_search_path(current_user) %> </button>
      <button class="btn btn-default" type="button"><%= link_to 'Recieved Request', requested_users_search_path(current_user) %> </button>
      <button class="btn btn-success" type="button"><%= link_to 'Match', matched_users_search_path(current_user) %> </button>
    </div>
  </div>
  <div class="search-city">
    <h2>Books in <%= @mylocation.city %></h2>
  </div>
  <% if @books.present? %>
    <% @books.each do |book| %>
      <div class="search-book">
        <div class="row">
          <aside class="col-xs-4">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title"><%= book.title %></h3>
              </div>
              <div class="panel-body">
                <img class="media-object img-rounded img-responsive" src="<%= book.image %>" alt="">
              </div>
            </div>
          </aside>
          <div class="col-xs-8">
            <h3>Owned by: <%= link_to book.user.profile.name, profile_path(id: book.user.profile.id) %></h3>
            <ul>
              <li>Author: <%= book.author %></li>
              <li>Language: <%= book.language %></li>
              <li><%= book.page %> Page</li>
              <li>Description: <%= book.description %></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-2">
            <%= render 'relationships/request_button', user: book.user %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/searches/matched_users.html.erb
<div>
  <h1>Match</h1>
  <ul>
    <% @match_users.each do |user| %>
      <li><%= link_to user.profile.name, profile_path(id: user.profile.id) %> who has <%= link_to user.book.title, book_path(user.book.id) %>></li>
      <%= render 'relationshipmessages/message_button', user: user, users: @match_users %>
    <% end %>
  </ul>
</div>
<div>
  <%= link_to 'Back to Search', searches_path %>
</div>

app/views/searches/request_users.html.erb
<div>
  <h1>Sent Request</h1>
  <ul>
    <% @request_users.each do |user| %>
      <li><%= link_to user.profile.name, profile_path(id: user.profile.id) %> : <%= link_to user.book.title, book_path(user.book.id) %></li>
      <%= render 'relationships/request_button', user: user %>
    <% end %>
  </ul>
</div>
<div>
  <%= link_to 'Back to Search', searches_path %>
</div>

app/views/searches/requested_users.html.erb
<div>
  <h1>Recieved Request for your <%= current_user.book.title %></h1>
  <ul>
    <% @requested_users.each do |user| %>
      <li><%= link_to user.profile.name, profile_path(id: user.profile.id) %> who has <%= link_to user.book.title, book_path(user.book.id) %></li>
      <%= render 'relationships/request_button', user: user %>
    <% end %>
  </ul>
</div>
<div>
  <%= link_to 'Back to Search', searches_path %>
</div>