config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] 
  patch 'mylocation', to: 'users#update_mylocation'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :books, only: [:show, :new, :create, :edit, :update]
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  resources :searches, only: [:index] do
    member do
      get :request_users
      get :requested_users
      get :matched_users
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :relationshipmessages, only: [:create, :destroy]
  resources :messages, only: [:index, :create]
  patch 'accept_trade1', to: 'trade1s#accept_trade1'
  patch 'cancel_trade1', to: 'trade1s#cancel_trade1'
  patch 'accept_trade2', to: 'trade2s#accept_trade2'
  patch 'cancel_trade2', to: 'trade2s#cancel_trade2'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :image, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :author, presence: true, length: { maximum: 50 }
  validates :language, presence: true, length: { maximum: 50 }
  validates :page, presence: true
  validates :description, presence: true, length: { maximum: 255 }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :mylocations
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: 'User'
  
  validates :user_id, presence: true
  validates :recipient_id, presence: true
  validates :content, presence: true, length: { maximum: 50 }
end

app/models/mylocation.rb
class Mylocation < ApplicationRecord
  belongs_to :country
  has_many :users
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :image, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :nationality, presence: true, length: { maximum: 50 }
  validates :gender, presence: true, length: { maximum: 50 }
  validates :age, presence: true
  validates :description, presence: true, length: { maximum: 255 }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :request, class_name: 'User'
  
  validates :user_id, presence: true
  validates :request_id, presence: true
end

app/models/trade1.rb
class Trade1 < ApplicationRecord
  belongs_to :user
  belongs_to :trader, class_name: 'User'
  
  validates :user_id, presence: true
  validates :trader_id, presence: true
end

app/models/trade2.rb
class Trade2 < ApplicationRecord
  belongs_to :user
  belongs_to :trader, class_name: 'User'
  
  validates :user_id, presence: true
  validates :trader_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  belongs_to :mylocation, optional: true
  has_one :book
  has_one :profile
  has_many :relationships
  has_many :requestings, through: :relationships, source: :request
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'request_id'
  has_many :requesteds, through: :reverses_of_relationship, source: :user
  has_many :relationshipmessages
  has_many :m_requestings, through: :relationshipmessages, source: :m_request
  has_many :reverses_of_relationshipmessage, class_name: 'Relationshipmessage', foreign_key: 'm_request_id'
  has_many :m_requesteds, through: :reverses_of_relationshipmessage, source: :user
  has_many :messages
  has_one :trade1
  has_one :trade2
  
  #Request & Unrequest button
  def send_request(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(request_id: other_user.id)
    end
  end
  
  def cancel_request(other_user)
    relationship = self.relationships.find_by(request_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def match_exist?(other_user)
    if self.requestings.include?(other_user) && self.requesteds.include?(other_user)
      return true
    else
      return false
    end
  end
  
  def requestings_exist?(other_user)
    self.requestings.include?(other_user)
  end
  
  #Message button
  def m_send_request(other_user)
    unless self == other_user
      self.relationshipmessages.find_or_create_by(m_request_id: other_user.id)
    end
  end
  
  def m_match_exist?(other_user)
    if self.m_requestings.include?(other_user) && self.m_requesteds.include?(other_user)
      return true
    else
      return false
    end
  end
  
  def m_match_in_users?(other_users)
    other_users.each do |user|
      if m_match_exist?(user)
        return true
      end
    end
    return false
  end
  
  def m_requestings_exist?(other_user)
    self.m_requestings.include?(other_user)
  end
  
  #After message_button is pushed
  def go_to_message(other_user)
    self.update(message_user_id: other_user.id)
    others = []
    other_relationships = self.relationshipmessages.where(user_id: self.id)
    other_relationships.each do |other|
      unless other.m_request_id == other_user.id
        others << other
      end
    end
    others.each do |other|
      other.destroy
    end
  end
  
  # Message 
  def send_message(other_user, content)
    unless self == other_user
      self.messages.build(recipient_id: other_user.id, content: content)
    end
  end
  
  #Trade1 button
  def trade1_accept_exchange(trade1)
    trade1.update(answer: 'Yes')
  end
  
  def trade1_cancel_exchange(trade1)
    trade1.update(answer: 'No')
  end
  
  def trade1_both_accept?(other_user)
    if other_user.trade1.present?
      if self.trade1.answer == 'Yes' && other_user.trade1.answer == 'Yes'
        return true
      else
        return false
      end
    else
      return false
    end
  end
  
  def trade1_user_accepted?(other_user)
    if self.trade1.answer == 'Yes' 
      return true
    else
      return false
    end
  end
  
  #Trade2 button
  def trade2_accept_exchange(trade2)
    trade2.update(answer: 'Yes')
  end
  
  def trade2_cancel_exchange(trade2)
    trade2.update(answer: 'No')
  end
  
  def trade2_user_accepted?(other_user)
    if self.trade2.answer == 'Yes' 
      return true
    else
      return false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/trade1s_helper.rb
module Trade1sHelper
end

app/helpers/trade2s_helper.rb
module Trade2sHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_mylocation.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">MyLocation<span class="caret"></span></a>
  <ul class="dropdown-menu multi-level">
    <% Country.all.each do |country| %>
      <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= country.name %></a>
      <ul class="dropdown-menu">
        <% Mylocation.where(country_id: country.id).each do |mylocation| %>
          <li><%= link_to mylocation.city, mylocation_path(mylocation_id: mylocation.id), method: :patch %></li>
        <% end %>
      </ul>
    <% end %>
  </ul>
</li>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Books in Backpack</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Search', searches_path %></li>
            <% if current_user.message_user_id.present? %>
              <li><%= link_to 'Message', messages_path(recipient_id: current_user.message_user_id) %></li>
            <% else %>
              <li><%= link_to 'Message', messages_path %></li>
            <% end %>
            <%= render 'layouts/mylocation' %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if current_user.profile.present? %>
                  <li><%= link_to 'My Profile', profile_path(id: current_user.profile.id) %></li>
                <% else %>
                  <li><%= link_to 'Create Profile', new_profile_path %></li>
                <% end %>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Books in Backpack</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>